application_name: "app-name"
port: 8080
image: "repo_url/project/image_name:tag"
resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 500m
nodeSelector:
  node_group: system-private
service:
  enabled: true
  # type: NodePort
  # protocol: TCP
ingress:
  enabled: true
  dns: frontendapp.dev.enterprisedomain.com.br
  # pathType: ImplementationSpecific
hpa:
  enabled: false
  min: 1
  max: 3
