{{ if .Values.configmap }}
{{ if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Values.application_name }}

data:
  {{- range $key, $val := .Values.configmap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{ end }}
{{ end }}